# Generated by Django 4.2 on 2024-12-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=50)),
                ('boss', models.BooleanField(default=False)),
                ('activ', models.BooleanField(default=True)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigade_employees', to='plant.brigade')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigade_repairs', to='plant.brigade')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='plant.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to='plant.employee')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_tasks', to='plant.repair')),
            ],
        ),
        migrations.AddField(
            model_name='brigade',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigade_leader', to='plant.employee'),
        ),
    ]
