# Generated by Django 4.2 on 2024-12-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_segment_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Объетк ремонта.'},
        ),
        migrations.AlterModelOptions(
            name='locationzone',
            options={'verbose_name': 'Локализация', 'verbose_name_plural': 'Локализации'},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Сегмент', 'verbose_name_plural': 'Сегменты'},
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='segment',
            new_name='name',
        ),
    ]
